package com.asus.activity;

import java.util.ArrayList;
import java.util.Random;

import com.asus.atc.dialogservice.DMListener;
import com.asus.atc.dialogservice.DMResult;
import com.asus.atc.dialogservice.DialogServiceConnector;
import com.asus.bubbles.BubblesArrayAdapter;
import com.asus.bubbles.OneComment;
import com.asus.data.DBHelper;
import com.asus.data.OntologyData;
import com.asus.data.loader.OntologyDataLoader;
import com.asus.dialogue.InputDispatcher;
import com.asus.dialogue.Question;
import com.asus.util.RandomUtil;

import android.app.Activity;
import android.app.LoaderManager.LoaderCallbacks;
import android.content.ActivityNotFoundException;
import android.content.ContentValues;
import android.content.Intent;
import android.content.Loader;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.speech.RecognizerIntent;

import android.util.Log;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ListView;

public class SentenceMakingActivity extends Activity implements LoaderCallbacks<Cursor>{

	// //////////////////////
	// /Debug
	// //////////////////////
	protected static final String TAG = SentenceMakingActivity.class
			.getSimpleName();

	// //////////////////////
	// /Member
	// //////////////////////
	private static Random random;
	private OntologyData ontologyData;
	private Question question;
	private Animation sentenceAnimation;
	private BubblesArrayAdapter adapter;
	private DialogServiceConnector dialogServiceConnector;

	protected static final int RESULT_SPEECH = 1;

	// /////////////////////
	// /UI
	// /////////////////////
	private ListView chatListView;
	private ImageButton answerButton;
	ImageView sentencePhoto;

	private void initView() {
		chatListView = (ListView) findViewById(R.id.chatListView);
		answerButton = (ImageButton) findViewById(R.id.answerButton);
		sentencePhoto = (ImageView) findViewById(R.id.sentence_photo);
		setUI();
	}

	private void setUI() {

		answerButton.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View view) {
				// Intent intent = new
				// Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
				// intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,
				// "en-US");
				// try {
				// startActivityForResult(intent, RESULT_SPEECH);
				// } catch (ActivityNotFoundException a) {
				// Toast t = Toast.makeText(getApplicationContext(),
				// "Opps! Your device doesn't support Speech to Text",
				// Toast.LENGTH_SHORT);
				// t.show();
				// }
				// dialogServiceConnector.bindService();
				dialogServiceConnector.startCSR();
			}
		});

		sentenceAnimation = AnimationUtils.loadAnimation(this,
				R.layout.quiz_animation);
		sentencePhoto.setAnimation(sentenceAnimation);

	}

	// /////////////////////
	// /LifeCycle
	// /////////////////////
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.sentence_making_activity);
		initView();

		random = new Random();
		ontologyData = OntologyData.getInstance();
		question = Question.getInstance();

		sentenceAnimation.start();
		
		Log.w(getClass().getSimpleName(), "onCreate");
		
		dialogServiceConnector = new DialogServiceConnector(this);
		final DMListener dmListener = new DMListener() {
			public void onResult(final DMResult dmResult) {
				if (dmResult != null) {
					String text = dmResult.getText().trim();
					adapter.add(new OneComment(false, text));
					InputDispatcher.getInstance(question, text, adapter)
							.start();
				} else {
				}
			}

			public void onConnected() {
				try {
					Thread.sleep(2000);
					dialogServiceConnector
							.responseToUser("歡迎來到造句遊戲，可愛的小朋友，可以開始玩造句囉");
					adapter = new BubblesArrayAdapter(getApplicationContext(),
							R.layout.bubble_listitem_view,
							dialogServiceConnector);
					chatListView.setAdapter(adapter);
					addRandomQuestion();
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			}

		};
		dialogServiceConnector.setSpeechListener(dmListener);
		
		/////////////
		//TEMP
		////////////
		this.deleteDatabase("ontology.db");
		getLoaderManager().initLoader(1, null, this);
		adapter = new BubblesArrayAdapter(getApplicationContext(),R.layout.bubble_listitem_view,dialogServiceConnector);
		
	}

	@Override
	protected void onResume() {
		// TODO Auto-generated method stub
		super.onResume();
		
	}

	protected void onDestroy() {
		super.onDestroy();
		//dialogServiceConnector.releaseService();
	}
	
	@Override
	protected void onStart() {
		// TODO Auto-generated method stub
		super.onStart();
		//this.deleteDatabase("ontology.db");
		DBHelper dbHelper = new DBHelper(this);
		//dialogServiceConnector.bindService();
		SQLiteDatabase database=dbHelper.getWritableDatabase();
		ContentValues values = new ContentValues();
		values.put(dbHelper.C_NOUN, "香蕉");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.banana);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "床");
		values.put(dbHelper.C_ADJ, "沉甸甸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bed);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛肉");
		values.put(dbHelper.C_ADJ, "白花花");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.beef);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛肉");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.beef);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛肉");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.beef);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛肉");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.beef);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛肉");
		values.put(dbHelper.C_ADJ, "血淋淋");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.beef);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳥");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bird);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳥");
		values.put(dbHelper.C_ADJ, "綠色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bird);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳥");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bird);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳥");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bird);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳥");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bird);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "書本");
		values.put(dbHelper.C_ADJ, "黑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.book);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "書本");
		values.put(dbHelper.C_ADJ, "黑漆漆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.book);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "書本");
		values.put(dbHelper.C_ADJ, "黑鴉鴉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.book);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "書本");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.book);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "書本");
		values.put(dbHelper.C_ADJ, "黑黝黝");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.book);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "鐵錚錚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑漆漆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑沉沉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑鴉鴉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "黑黝黝");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "沉甸甸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋子");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bowl);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "暖呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "熱呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "熱烘烘");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵包");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛋糕");
		values.put(dbHelper.C_ADJ, "甜蜜蜜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛋糕");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "甘蔗");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cane);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "甘蔗");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cane);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "甘蔗");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cane);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "文蛤");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.clam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "文蛤");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.clam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "文蛤");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.clam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "文蛤");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.clam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "哈密瓜");
		values.put(dbHelper.C_ADJ, "甜蜜蜜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cantaloupe);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椅子");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chair);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椅子");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chair);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椅子");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chair);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椅子");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chair);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椅子");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chair);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "起司");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cheese);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "櫻桃");
		values.put(dbHelper.C_ADJ, "紅撲撲");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cherry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "櫻桃");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cherry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "櫻桃");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cherry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "櫻桃");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cherry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞肉");
		values.put(dbHelper.C_ADJ, "白嫩嫩");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chicken);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞肉");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chicken);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞肉");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chicken);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "筷子");
		values.put(dbHelper.C_ADJ, "直挺挺");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.chopsticks);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "衣服");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cloth);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cockrooster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞");
		values.put(dbHelper.C_ADJ, "毛茸茸圓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cockrooster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞");
		values.put(dbHelper.C_ADJ, "鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cockrooster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞");
		values.put(dbHelper.C_ADJ, "土黃色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cockrooster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椰子");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.coconut);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "椰子");
		values.put(dbHelper.C_ADJ, "毛絨絨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.coconut);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "可樂");
		values.put(dbHelper.C_ADJ, "甜甜的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.coke);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "可樂");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.coke);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "可樂");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.coke);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棉被");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.comforter);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棉被");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.comforter);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棉被");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.comforter);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棉被");
		values.put(dbHelper.C_ADJ, "軟趴趴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.comforter);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棉被");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.comforter);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電腦");
		values.put(dbHelper.C_ADJ, "正方方的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.computer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "餅乾");
		values.put(dbHelper.C_ADJ, "脆脆的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cookie);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "餅乾");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cookie);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "玉米");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.corn);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "玉米");
		values.put(dbHelper.C_ADJ, "香噴噴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.corn);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "玉米");
		values.put(dbHelper.C_ADJ, "熱騰騰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.corn);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "玉米");
		values.put(dbHelper.C_ADJ, "熱呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.corn);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "玉米");
		values.put(dbHelper.C_ADJ, "熱烘烘");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.corn);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛");
		values.put(dbHelper.C_ADJ, "慢吞吞");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛");
		values.put(dbHelper.C_ADJ, "黃褐色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蟹");
		values.put(dbHelper.C_ADJ, "光禿禿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.crab);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "奶油");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.cream);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "活蹦亂跳的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "土黃色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鹿");
		values.put(dbHelper.C_ADJ, "怯生生");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.deer);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "碗盤");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "碗盤");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "碗盤");
		values.put(dbHelper.C_ADJ, "亮晶晶");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "碗盤");
		values.put(dbHelper.C_ADJ, "光溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "碗盤");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "狗");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dog);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "狗");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dog);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "狗");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dog);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "狗");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dog);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "狗");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dog);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "長長的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "迅速的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "灰色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "海豚");
		values.put(dbHelper.C_ADJ, "聰明的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.dolphin);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鴨");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.duck);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鴨");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.duck);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鴨");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.duck);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鴨");
		values.put(dbHelper.C_ADJ, "白色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.duck);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "榴槤");
		values.put(dbHelper.C_ADJ, "香噴噴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.durian);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "雞蛋");
		values.put(dbHelper.C_ADJ, "光溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.egg);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚");
		values.put(dbHelper.C_ADJ, "腥腥的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚");
		values.put(dbHelper.C_ADJ, "滑滑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚肉");
		values.put(dbHelper.C_ADJ, "白花花");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish_meat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚肉");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish_meat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚肉");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish_meat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚肉");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish_meat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "魚肉");
		values.put(dbHelper.C_ADJ, "血淋淋");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fish_meat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "鐵錚錚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "冷冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "亮光光");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "叉子");
		values.put(dbHelper.C_ADJ, "亮晶晶");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.fork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "長頸鹿");
		values.put(dbHelper.C_ADJ, "高高的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.giraffe);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "長頸鹿");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.giraffe);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "長頸鹿");
		values.put(dbHelper.C_ADJ, "直愣愣");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.giraffe);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "長頸鹿");
		values.put(dbHelper.C_ADJ, "直挺挺");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.giraffe);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鵝");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.goose);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鵝");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.goose);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鵝");
		values.put(dbHelper.C_ADJ, "白色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.goose);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鵝");
		values.put(dbHelper.C_ADJ, "優雅的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.goose);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "葡萄");
		values.put(dbHelper.C_ADJ, "甜滋滋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.grape);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "葡萄柚");
		values.put(dbHelper.C_ADJ, "酸孜孜的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.grapefruit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "芭樂");
		values.put(dbHelper.C_ADJ, "澀澀的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.guava);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "火腿");
		values.put(dbHelper.C_ADJ, "鹹鹹的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.ham);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "胖嘟嘟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "溼答答");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "溼淋淋");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "溼漉漉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "粉紅色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "河馬");
		values.put(dbHelper.C_ADJ, "皺巴巴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.hippo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬");
		values.put(dbHelper.C_ADJ, "棕色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.horse);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬");
		values.put(dbHelper.C_ADJ, "迅速的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.horse);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬");
		values.put(dbHelper.C_ADJ, "跑得快的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.horse);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "冰淇淋");
		values.put(dbHelper.C_ADJ, "甜滋滋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.icecream);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "泡麵");
		values.put(dbHelper.C_ADJ, "熱騰騰的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.instant_noodles);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "果汁");
		values.put(dbHelper.C_ADJ, "甜甜的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.juice);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "棗子");
		values.put(dbHelper.C_ADJ, "硬硬的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.jujube);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "奇異果");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.kiwi);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "奇異果");
		values.put(dbHelper.C_ADJ, "毛絨絨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.kiwi);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "檸檬");
		values.put(dbHelper.C_ADJ, "酸溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.lemon);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "獅子");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.lion);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "獅子");
		values.put(dbHelper.C_ADJ, "土黃色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.lion);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "獅子");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.lion);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "獅子");
		values.put(dbHelper.C_ADJ, "兇猛的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.lion);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "荔枝");
		values.put(dbHelper.C_ADJ, "甜甜的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.litchi);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "龍眼");
		values.put(dbHelper.C_ADJ, "甜甜的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.longyan);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "枇杷");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.loquat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "芒果");
		values.put(dbHelper.C_ADJ, "黏答答");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mango);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "芒果");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mango);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛奶");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.milk);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛奶");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.milk);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牛奶");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.milk);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "猴子");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.monkey);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "猴子");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.monkey);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "猴子");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.monkey);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "猴子");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.monkey);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "猴子");
		values.put(dbHelper.C_ADJ, "聰明的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.monkey);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "香瓜");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.muskmelon);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊肉");
		values.put(dbHelper.C_ADJ, "白花花");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mutton);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊肉");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mutton);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊肉");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mutton);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊肉");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.mutton);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.noodles);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.noodles);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.noodles);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "麵");
		values.put(dbHelper.C_ADJ, "鬆垮垮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.noodles);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "章魚");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.octopus);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "章魚");
		values.put(dbHelper.C_ADJ, "軟趴趴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.octopus);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "章魚");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.octopus);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "橘子");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.orange);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蚵仔");
		values.put(dbHelper.C_ADJ, "軟趴趴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.oyster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蚵仔");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.oyster);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓熊");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.panda);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓熊");
		values.put(dbHelper.C_ADJ, "黑白色");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.panda);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓熊");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.panda);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "貓熊");
		values.put(dbHelper.C_ADJ, "胖嘟嘟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.panda);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "褲子");
		values.put(dbHelper.C_ADJ, "皺巴巴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pants);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "褲子");
		values.put(dbHelper.C_ADJ, "鬆垮垮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pants);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "木瓜");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.papaya);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "紙");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.paper);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桃");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.peach);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桃");
		values.put(dbHelper.C_ADJ, "白嫩嫩");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.peach);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桃");
		values.put(dbHelper.C_ADJ, "甜蜜蜜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.peach);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桃");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.peach);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "梨子");
		values.put(dbHelper.C_ADJ, "胖嘟嘟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pear);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "梨子");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pear);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "筆");
		values.put(dbHelper.C_ADJ, "直挺挺");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pen);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "柿子");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.persimmon);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "黑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "黑漆漆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "黑鴉鴉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "烏溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "手機");
		values.put(dbHelper.C_ADJ, "烏亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.phone);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "洋芋片");
		values.put(dbHelper.C_ADJ, "油漬漬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.photo_chip);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "洋芋片");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.photo_chip);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "洋芋片");
		values.put(dbHelper.C_ADJ, "油膩膩");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.photo_chip);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬");
		values.put(dbHelper.C_ADJ, "胖嘟嘟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pig);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pig);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬");
		values.put(dbHelper.C_ADJ, "粉紅色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pig);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pig);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "枕頭");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pillow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "枕頭");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pillow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "枕頭");
		values.put(dbHelper.C_ADJ, "蓬鬆鬆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pillow);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鳳梨");
		values.put(dbHelper.C_ADJ, "黃澄澄");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pineapple);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "李子");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.plum);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "柚子");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pomelo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "白花花");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "油膩膩");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豬肉");
		values.put(dbHelper.C_ADJ, "血淋淋");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pork);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬鈴薯");
		values.put(dbHelper.C_ADJ, "乾癟癟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.potato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬鈴薯");
		values.put(dbHelper.C_ADJ, "乾巴巴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.potato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "布丁");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.pudding);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "灰灰的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "灰色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "跑得快的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "兔");
		values.put(dbHelper.C_ADJ, "怯生生");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rabbit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鼠");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鼠");
		values.put(dbHelper.C_ADJ, "土黃色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鼠");
		values.put(dbHelper.C_ADJ, "活潑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鼠");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鼠");
		values.put(dbHelper.C_ADJ, "怯生生");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rat);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "白飯");
		values.put(dbHelper.C_ADJ, "熱烘烘");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rice);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "白飯");
		values.put(dbHelper.C_ADJ, "熱呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rice);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "白飯");
		values.put(dbHelper.C_ADJ, "熱騰騰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.rice);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "沙拉醬");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.salad_dressing);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "洗髮精");
		values.put(dbHelper.C_ADJ, "香噴噴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shampoo);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯊魚");
		values.put(dbHelper.C_ADJ, "長長的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shark);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯊魚");
		values.put(dbHelper.C_ADJ, "迅速的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shark);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯊魚");
		values.put(dbHelper.C_ADJ, "靈敏的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shark);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯊魚");
		values.put(dbHelper.C_ADJ, "黑白色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shark);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sheep);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sheep);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊");
		values.put(dbHelper.C_ADJ, "白色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sheep);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "羊");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sheep);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蝦");
		values.put(dbHelper.C_ADJ, "活蹦蹦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shrimp);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蝦");
		values.put(dbHelper.C_ADJ, "活跳跳");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.shrimp);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛇");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.snake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛇");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.snake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛇");
		values.put(dbHelper.C_ADJ, "長長的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.snake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛇");
		values.put(dbHelper.C_ADJ, "滑滑的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.snake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蛇");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.snake);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "肥皂");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.soap);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "肥皂");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.soap);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "汽水");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.soda_drink);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "汽水");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.soda_drink);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "沙發");
		values.put(dbHelper.C_ADJ, "緊繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sofa);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "沙發");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sofa);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "沙發");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sofa);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "沙發");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sofa);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "烏亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "黑鴉鴉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "黑漆漆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鍋鏟");
		values.put(dbHelper.C_ADJ, "黑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.spatula);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "花枝");
		values.put(dbHelper.C_ADJ, "滑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.squid);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "花枝");
		values.put(dbHelper.C_ADJ, "軟趴趴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.squid);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "花枝");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.squid);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "楊桃");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.star_fruit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "楊桃");
		values.put(dbHelper.C_ADJ, "酸溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.star_fruit);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "饅頭");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.steamed_bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "饅頭");
		values.put(dbHelper.C_ADJ, "熱烘烘");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.steamed_bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "饅頭");
		values.put(dbHelper.C_ADJ, "熱呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.steamed_bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "饅頭");
		values.put(dbHelper.C_ADJ, "熱騰騰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.steamed_bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "饅頭");
		values.put(dbHelper.C_ADJ, "暖呼呼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.steamed_bread);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "草莓");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.strawberry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "草莓");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.strawberry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "草莓");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.strawberry);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "釋迦");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.sugar_apple);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桌子");
		values.put(dbHelper.C_ADJ, "硬梆梆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.table);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桌子");
		values.put(dbHelper.C_ADJ, "硬繃繃");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.table);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "桌子");
		values.put(dbHelper.C_ADJ, "硬邦邦");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.table);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "老虎");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tiger);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "老虎");
		values.put(dbHelper.C_ADJ, "黃黑色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tiger);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "老虎");
		values.put(dbHelper.C_ADJ, "兇猛的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tiger);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "老虎");
		values.put(dbHelper.C_ADJ, "毛茸茸");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tiger);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "土司");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toast);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豆腐");
		values.put(dbHelper.C_ADJ, "白嫩嫩");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tofu);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豆腐");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tofu);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豆腐");
		values.put(dbHelper.C_ADJ, "白皙皙");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tofu);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豆腐");
		values.put(dbHelper.C_ADJ, "軟趴趴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tofu);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "豆腐");
		values.put(dbHelper.C_ADJ, "軟綿綿");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tofu);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬桶");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toilet);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬桶");
		values.put(dbHelper.C_ADJ, "冰涼涼");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toilet);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬桶");
		values.put(dbHelper.C_ADJ, "冷冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toilet);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "馬桶");
		values.put(dbHelper.C_ADJ, "涼冰冰");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toilet);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "番茄");
		values.put(dbHelper.C_ADJ, "紅撲撲");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tomato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "番茄");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tomato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "番茄");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tomato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "番茄");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tomato);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牙刷");
		values.put(dbHelper.C_ADJ, "長長的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toothbrush);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "牙膏");
		values.put(dbHelper.C_ADJ, "涼涼的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.toothpaste);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "烏龜");
		values.put(dbHelper.C_ADJ, "慢吞吞");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.turtle);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "烏龜");
		values.put(dbHelper.C_ADJ, "橢圓形的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.turtle);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "烏龜");
		values.put(dbHelper.C_ADJ, "灰色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.turtle);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "烏龜");
		values.put(dbHelper.C_ADJ, "緩慢的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.turtle);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "烏龜");
		values.put(dbHelper.C_ADJ, "慢慢的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.turtle);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑漆漆");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑沉沉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑鴉鴉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑壓壓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "黑黝黝");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "電視");
		values.put(dbHelper.C_ADJ, "烏亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.tv);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "內衣");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.underclothes);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "內褲");
		values.put(dbHelper.C_ADJ, "白淨淨");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.underwear);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蔬菜");
		values.put(dbHelper.C_ADJ, "綠油油");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.vegetable);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蔬菜");
		values.put(dbHelper.C_ADJ, "溼答答");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.vegetable);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蔬菜");
		values.put(dbHelper.C_ADJ, "溼淋淋");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.vegetable);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蔬菜");
		values.put(dbHelper.C_ADJ, "溼漉漉");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.vegetable);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蔬菜");
		values.put(dbHelper.C_ADJ, "油亮亮");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.vegetable);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "西瓜");
		values.put(dbHelper.C_ADJ, "圓鼓鼓");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.watermelon);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "蓮霧");
		values.put(dbHelper.C_ADJ, "紅通通的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.wax_apple);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯨魚");
		values.put(dbHelper.C_ADJ, "巨大的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.whale);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯨魚");
		values.put(dbHelper.C_ADJ, "龐大的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.whale);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯨魚");
		values.put(dbHelper.C_ADJ, "慢吞吞");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.whale);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯨魚");
		values.put(dbHelper.C_ADJ, "溫馴的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.whale);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "鯨魚");
		values.put(dbHelper.C_ADJ, "和善的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.whale);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "地瓜");
		values.put(dbHelper.C_ADJ, "乾癟癟");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "地瓜");
		values.put(dbHelper.C_ADJ, "乾巴巴");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "地瓜");
		values.put(dbHelper.C_ADJ, "紅冬冬");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "地瓜");
		values.put(dbHelper.C_ADJ, "紅咚咚");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "地瓜");
		values.put(dbHelper.C_ADJ, "紅通通");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yam);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "優格");
		values.put(dbHelper.C_ADJ, "酸溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yogurt);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "優酪乳");
		values.put(dbHelper.C_ADJ, "酸溜溜");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.yogurt_milk);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "斑馬");
		values.put(dbHelper.C_ADJ, "黑白色的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.zebra);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "斑馬");
		values.put(dbHelper.C_ADJ, "有花紋的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.zebra);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "斑馬");
		values.put(dbHelper.C_ADJ, "怯生生");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.zebra);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		values.put(dbHelper.C_NOUN, "斑馬");
		values.put(dbHelper.C_ADJ, "跑得快的");
		values.put(dbHelper.C_PHOTO_ID, R.drawable.zebra);
		database.insertOrThrow(dbHelper.TABLE_NAME, null, values);
		database.close();
	}

	// /////////////////////
	// /Methods
	// /////////////////////
	private void addRandomQuestion() {

		// randomly ask adj or noun
		if (RandomUtil.getRandomInteger(0, 1) == 0 ? true : false) {
			question.questionPhrase = ontologyData.getOneRandomNoun();
			question.isAskingAdj = true;
			adapter.add(new OneComment(true, "試試看這個句子。  ______的"
					+ question.questionPhrase));
		} else {
			question.questionPhrase = ontologyData.getOneRandomAdj();
			question.isAskingAdj = false;
			adapter.add(new OneComment(true, "試試看這個句子。  "
					+ question.questionPhrase + "______"));
		}
	}


	@Override
	public Loader<Cursor> onCreateLoader(int arg0, Bundle arg1) {
		// TODO Auto-generated method stub
		return new OntologyDataLoader(getApplicationContext());
	}

	@Override
	public void onLoadFinished(Loader<Cursor> loader, Cursor cursor) {
		// TODO Auto-generated method stub
		while(cursor.moveToNext()){
//	
//	adapter.add(new OneComment(true, cursor.getString(0)));
			Log.w(getClass().getSimpleName(), cursor.getString(0));
//	System.out.print(cursor.getString(0));
//	
		}
		cursor.close();
		
	}

	@Override
	public void onLoaderReset(Loader<Cursor> arg0) {
		// TODO Auto-generated method stub
		
	}

}
